// search-engine.js — Da Nang Hotel Guide search engine v2
// Full 174-entry index with intent-based ranking
// Injected on all pages — replaces stale inline SEARCH_INDEX

(function() {

window.SI = [
  {t:'Da Nang Hotels 2026 — Best Picks, Honest Reviews & Local Advice',u:'index.html',c:'Homepage',e:'Da Nang hotels ranked by a local who lives here. Luxury resorts, beach hotels, budget picks — honest reviews, real prices, no paid placements. Updated 2026.',p:100,k:'da nang hotels 2026 — best picks, honest reviews & local advice da nang hotels ranked by a local who lives here. luxury resorts, beach hotels, budget picks — honest reviews, real prices, no paid placements. updated 2026. index'},
  {t:'25 Best Hotels in Da Nang 2026 — Ranked by a Local Expat',u:'best-hotels-in-da-nang.html',c:'Hotels Hub',e:'Da Nang\'s 25 best hotels for 2026, ranked honestly by a local who lives here. Beach resorts, luxury picks, budget gems — with real prices and zero paid place...',p:99,k:'25 best hotels in da nang 2026 — ranked by a local expat da nang\'s 25 best hotels for 2026, ranked honestly by a local who lives here. beach resorts, luxury picks, budget gems — with real prices and zero paid place... best hotels in da nang'},
  {t:'Where to Stay in Da Nang: Best Areas for Every Traveler',u:'where-to-stay-in-da-nang.html',c:'Area Guide',e:'Not sure where to stay in Da Nang? Compare My Khe Beach, Han River, An Thuong, Non Nuoc, Son Tra, and Hoi An by travel style, budget, and hotel type.',p:98,k:'where to stay in da nang: best areas for every traveler not sure where to stay in da nang? compare my khe beach, han river, an thuong, non nuoc, son tra, and hoi an by travel style, budget, and hotel type. where to stay in da nang'},
  {t:'Best Luxury Hotels in Da Nang 2026 — 5-Star Resorts Ranked',u:'luxury-hotels-da-nang.html',c:'Luxury Hotels',e:'InterContinental, Hyatt Regency, Sheraton Grand, Fusion Maia — Da Nang',p:97,k:'best luxury hotels in da nang 2026 — 5-star resorts ranked intercontinental, hyatt regency, sheraton grand, fusion maia — da nang luxury hotels da nang'},
  {t:'Best Beach Hotels in Da Nang 2026 — My Khe & Non Nuoc',u:'da-nang-beach-hotels.html',c:'Beach Hotels',e:'The best beachfront hotels on My Khe and Non Nuoc Beach, ranked by a local. Direct sand access, honest trade-offs, prices from $40/night. Updated 2026.',p:96,k:'best beach hotels in da nang 2026 — my khe & non nuoc the best beachfront hotels on my khe and non nuoc beach, ranked by a local. direct sand access, honest trade-offs, prices from $40/night. updated 2026. da nang beach hotels'},
  {t:'Best Family Hotels in Da Nang 2026 — Kids Clubs, Pools & Honest Picks',u:'family-hotels-da-nang.html',c:'Family Hotels',e:'The best family resorts in Da Nang for 2026: Sheraton Grand, Hyatt Regency, Mikazuki. Kids clubs, waterparks, connecting rooms — honest picks from a local dad perspective.',p:95,k:'best family hotels in da nang 2026 — kids clubs, pools & honest picks the best family resorts in da nang for 2026: sheraton grand, hyatt regency, mikazuki. kids clubs, waterparks, connecting rooms — honest picks from a local dad perspective. family hotels da nang'},
  {t:'Best Boutique Hotels in Da Nang 2026 — Small, Local & Worth It',u:'boutique-hotels-da-nang.html',c:'Boutique Hotels',e:'Da Nang\'s best boutique hotels in An Thuong and My Khe. Character, design, and local personality from $45/night. Honest picks, no cookie-cutter chains.',p:94,k:'best boutique hotels in da nang 2026 — small, local & worth it da nang\'s best boutique hotels in an thuong and my khe. character, design, and local personality from $45/night. honest picks, no cookie-cutter chains. boutique hotels da nang'},
  {t:'Da Nang for First-Time Visitors 2026 — Start Here',u:'da-nang-first-time-visitors.html',c:'First-Time Guide',e:'First trip to Da Nang? A local',p:93,k:'first time visitor guide start here beginner tips da nang for first-time visitors 2026 — start here first trip to da nang? a local da nang first time visitors'},
  {t:'Best Time to Visit Da Nang 2026, When to Go?',u:'best-time-to-visit-da-nang.html',c:'Weather',e:'Best time to visit Da Nang 2026: dry season Feb–Aug, cheapest rates Apr–May & Sep–Oct, busiest Jun–Aug. Monthly weather, prices, and crowd levels explained.',p:92,k:'best time to visit da nang 2026, when to go? best time to visit da nang 2026: dry season feb–aug, cheapest rates apr–may & sep–oct, busiest jun–aug. monthly weather, prices, and crowd levels explained. best time to visit da nang'},
  {t:'3-Day Da Nang Itinerary 2026 — Local\'s Guide to Every Day',u:'da-nang-itinerary.html',c:'Itinerary',e:'The best 3-day Da Nang itinerary, written by a local expat. Beach, Marble Mountains, Hoi An day trip, Dragon Bridge — all timed and practical.',p:91,k:'3-day da nang itinerary 2026 — local\'s guide to every day the best 3-day da nang itinerary, written by a local expat. beach, marble mountains, hoi an day trip, dragon bridge — all timed and practical. da nang itinerary'},
  {t:'Da Nang 3-Day Itinerary 2026 — Day-by-Day Guide',u:'da-nang-3-day-itinerary.html',c:'Itinerary',e:'The best 3-day Da Nang itinerary for 2026. Day-by-day breakdown with timing, what to skip, and honest advice from a local resident.',p:90,k:'da nang 3-day itinerary 2026 — day-by-day guide the best 3-day da nang itinerary for 2026. day-by-day breakdown with timing, what to skip, and honest advice from a local resident. da nang 3 day itinerary'},
  {t:'Hoi An Travel Guide 2026 — A Local\'s Complete Overview',u:'hoi-an.html',c:'Hoi An',e:'Hoi An in 2026: the Ancient Town, An Bang Beach, where to stay, day-trip logistics from Da Nang, and honest advice from someone who visits regularly.',p:89,k:'hoi an ancient town lanterns old town cycling day trip from da nang hoi an travel guide 2026 — a local\'s complete overview hoi an in 2026: the ancient town, an bang beach, where to stay, day-trip logistics from da nang, and honest advice from someone who visits regularly. hoi an'},
  {t:'Where to Stay in Hoi An 2026, Best Areas Explained',u:'where-to-stay-in-hoi-an.html',c:'Hoi An',e:'Where to stay in Hoi An in 2026, Ancient Town, riverside, An Bang Beach, Cua Dai, or countryside? Detailed area guide with hotel picks, pros, cons, and honest advice.',p:88,k:'hoi an where to stay ancient town an bang beach cua dai riverside where to stay in hoi an 2026, best areas explained where to stay in hoi an in 2026, ancient town, riverside, an bang beach, cua dai, or countryside? detailed area guide with hotel picks, pros, cons, and honest advice. where to stay in'},
  {t:'Best Hotels in Hoi An 2026, Ancient Town to Beach',u:'best-hotels-in-hoi-an.html',c:'Hoi An',e:'The best hotels in Hoi An for 2026, from Ancient Town boutiques to An Bang beach resorts. Independently curated with real prices and local advice.',p:87,k:'hoi an hotels boutique ancient town romantic poolside best hotels in hoi an 2026, ancient town to beach the best hotels in hoi an for 2026, from ancient town boutiques to an bang beach resorts. independently curated with real prices and local advice. best hotels in hoi an'},
  {t:'Da Nang vs Hoi An 2026 — Which City Should You Base In?',u:'da-nang-vs-hoi-an.html',c:'Comparison',e:'Da Nang or Hoi An — where should you stay in 2026? An honest local comparison: beach, hotel value, nightlife, costs, and day-trip logistics.',p:86,k:'da nang vs hoi an which city base comparison da nang vs hoi an 2026 — which city should you base in? da nang or hoi an — where should you stay in 2026? an honest local comparison: beach, hotel value, nightlife, costs, and day-trip logistics. da nang vs hoi an'},
  {t:'Da Nang Dining Guide: Where to Eat Near the Best Hotel Areas',u:'dining.html',c:'Dining & Food',e:'Explore where to eat in Da Nang by hotel area, My Khe Beach, An Thuong, Han River, Dragon Bridge, and resort districts. MICHELIN-listed and local picks.',p:85,k:'dining food restaurants eat eating where to eat michelin cafes bars cuisine pho banh mi breakfast lunch dinner da nang dining guide: where to eat near the best hotel areas explore where to eat in da nang by hotel area, my khe beach, an thuong, han river, dragon bridge, and resort districts. michelin'},
  {t:'Da Nang Food Guide 2026 — What to Eat and Where',u:'da-nang-food-guide.html',c:'Dining & Food',e:'The best food in Da Nang 2026. Local dishes to try, where to eat them, restaurant areas, and honest advice from a local resident.',p:84,k:'food dining restaurants local dishes eat pho banh mi cuisine street food where to eat da nang food guide 2026 — what to eat and where the best food in da nang 2026. local dishes to try, where to eat them, restaurant areas, and honest advice from a local resident. da nang food guide'},
  {t:'Best Things to Do in Da Nang 2026 — A Local\'s Pick List',u:'things-to-do-in-da-nang.html',c:'Attractions',e:'The best things to do in Da Nang in 2026, ranked honestly. Beach, Dragon Bridge, Marble Mountains, Ba Na Hills, Hoi An day trips — and what to skip.',p:83,k:'best things to do in da nang 2026 — a local\'s pick list the best things to do in da nang in 2026, ranked honestly. beach, dragon bridge, marble mountains, ba na hills, hoi an day trips — and what to skip. things to do in da nang'},
  {t:'Da Nang Transport Guide 2026 — Getting Around Like a Local',u:'da-nang-transport-guide.html',c:'Transport',e:'How to get around Da Nang in 2026: Grab, motorbike hire, airport transfers, Hoi An trips. Honest transport guide from a local expat.',p:82,k:'transport getting around motorbike grab taxi bus scooter hire transport da nang transport guide 2026 — getting around like a local how to get around da nang in 2026: grab, motorbike hire, airport transfers, hoi an trips. honest transport guide from a local expat. da nang transport guide'},
  {t:'Da Nang Budget Guide 2026 — Real Costs from a Local',u:'da-nang-budget-guide.html',c:'Budget & Costs',e:'What Da Nang actually costs in 2026: hotels, food, transport, activities. Budget breakdown for every traveler type from a local who lives here.',p:81,k:'budget cost how much money trip spending da nang budget guide 2026 — real costs from a local what da nang actually costs in 2026: hotels, food, transport, activities. budget breakdown for every traveler type from a local who lives here. da nang budget guide'},
  {t:'Best Budget Hotels in Da Nang: Cheap Hotels That Still Feel Good',u:'best-budget-hotels-in-da-nang.html',c:'Budget Hotels',e:'Find the best budget hotels in Da Nang by area, traveler type, and real value. Compare cheap beach hotels, riverfront stays, under-$50 options, and budget hotels worth avoiding.',p:80,k:'best budget hotels in da nang: cheap hotels that still feel good find the best budget hotels in da nang by area, traveler type, and real value. compare cheap beach hotels, riverfront stays, under-$50 options, and budget hotels worth avoiding. best budget hotels in da nang'},
  {t:'Da Nang Digital Nomad Guide 2026 — A Local\'s Honest Take',u:'da-nang-digital-nomad-guide.html',c:'Expat & Long Stay',e:'Da Nang as a digital nomad base in 2026: internet speeds, coworking spaces, visa options, cost of living, and the neighbourhoods that actually work.',p:79,k:'digital nomad remote work coworking internet cafe visa long stay da nang digital nomad guide 2026 — a local\'s honest take da nang as a digital nomad base in 2026: internet speeds, coworking spaces, visa options, cost of living, and the neighbourhoods that actually work. da nang digital nomad guide'},
  {t:'Da Nang Weather by Month: Best and Worst Times to Visit Da Nang',u:'da-nang-weather-by-month.html',c:'Weather',e:'Plan your trip with a month-by-month Da Nang weather guide covering heat, rain, beach conditions, crowds, and hotel booking tips.',p:78,k:'da nang weather by month: best and worst times to visit da nang plan your trip with a month-by-month da nang weather guide covering heat, rain, beach conditions, crowds, and hotel booking tips. da nang weather by month'},
  {t:'25 Best Bars in Da Nang 2026 — Rooftops to Hidden Spots',u:'best-bars-in-da-nang.html',c:'Bars & Nightlife',e:'Da Nang\'s 25 best bars in 2026: rooftop venues, craft beer taprooms, cocktail bars, beach clubs. Ranked by a local with no sponsored picks.',p:77,k:'bars nightlife rooftop drinks cocktails beer craft beer bar scene happy hour 25 best bars in da nang 2026 — rooftops to hidden spots da nang\'s 25 best bars in 2026: rooftop venues, craft beer taprooms, cocktail bars, beach clubs. ranked by a local with no sponsored picks. best bars in da nang'},
  {t:'Da Nang Nightlife Guide 2026 — Bars, Clubs & Dragon Bridge',u:'da-nang-nightlife-guide.html',c:'Bars & Nightlife',e:'Da Nang\'s nightlife in 2026: the best bars, rooftops, Dragon Bridge fire show, and where to go depending on your night. Local expat guide, updated.',p:76,k:'nightlife bars clubs dragon bridge evening night out entertainment rooftop da nang nightlife guide 2026 — bars, clubs & dragon bridge da nang\'s nightlife in 2026: the best bars, rooftops, dragon bridge fire show, and where to go depending on your night. local expat guide, updated. da nang nightlife'},
  {t:'InterContinental Danang Sun Peninsula — Full Review 2026',u:'review-intercontinental-da-nang.html',c:'Hotel Review',e:'Full review of the InterContinental Danang Sun Peninsula Resort. Bill Bensley',p:75,k:'intercontinental danang sun peninsula — full review 2026 full review of the intercontinental danang sun peninsula resort. bill bensley review intercontinental da nang'},
  {t:'Marble Mountains Da Nang 2026 — Worth Visiting? Honest Guide',u:'marble-mountains-da-nang.html',c:'Attractions',e:'Is the Marble Mountains worth your time in 2026? Honest guide: what to see, how long to spend, best time to visit, and how to avoid the crowds.',p:75,k:'marble mountains non nuoc caves pagoda chua tam thai attraction landmarks hiking climbing marble mountains da nang 2026 — worth visiting? honest guide is the marble mountains worth your time in 2026? honest guide: what to see, how long to spend, best time to visit, and how to avoid the crowds. marbl'},
  {t:'My Khe Beach Da Nang: Local Guide 2026, Best Stretch?',u:'my-khe-beach-da-nang.html',c:'Beach & Coastal',e:'My Khe Beach Da Nang guide 2026, best stretch to stay on, swimming safety by month, rip current warning, and the top hotels for each section of the beach.',p:75,k:'my khe beach swimming surfing waves beach safety best stretch hotels my khe beach da nang: local guide 2026, best stretch? my khe beach da nang guide 2026, best stretch to stay on, swimming safety by month, rip current warning, and the top hotels for each section of the beach. my khe beach da nang'},
  {t:'Hyatt Regency Da Nang Resort — Full Review 2026',u:'review-hyatt-regency-da-nang.html',c:'Hotel Review',e:'Full Hyatt Regency Da Nang review 2026. 6 pools, lazy river, Non Nuoc beachfront. Best family resort in Da Nang? Honest assessment with real prices.',p:74,k:'hyatt regency da nang resort — full review 2026 full hyatt regency da nang review 2026. 6 pools, lazy river, non nuoc beachfront. best family resort in da nang? honest assessment with real prices. review hyatt regency da nang'},
  {t:'Sheraton Grand Da Nang Resort — Full Review 2026',u:'review-sheraton-grand-da-nang.html',c:'Hotel Review',e:'Full Sheraton Grand Da Nang review. Best family water complex in the city, 785 rooms, direct beachfront. Who it suits and what the trade-offs are.',p:73,k:'sheraton grand da nang resort — full review 2026 full sheraton grand da nang review. best family water complex in the city, 785 rooms, direct beachfront. who it suits and what the trade-offs are. review sheraton grand da nang'},
  {t:'Dragon Bridge Da Nang: Fire Show Guide 2026',u:'dragon-bridge-da-nang.html',c:'Attractions',e:'Dragon Bridge Da Nang fire & water show 2026: Fri, Sat & Sun at 9 PM, free to watch. Best viewing spots, arrival times, nearby restaurants, and insider tips.',p:73,k:'dragon bridge fire water show han river night landmark attraction weekend dragon bridge da nang: fire show guide 2026 dragon bridge da nang fire & water show 2026: fri, sat & sun at 9 pm, free to watch. best viewing spots, arrival times, nearby restaurants, and insider tips. dragon bridge da nang'},
  {t:'Naman Retreat Da Nang — Full Review 2026',u:'review-naman-retreat-da-nang.html',c:'Hotel Review',e:'Full Naman Retreat Da Nang review 2026. Bamboo architecture, spa, quiet beach between My Khe and Hoi An. Best couples/honeymoon resort in Da Nang?',p:72,k:'naman retreat da nang — full review 2026 full naman retreat da nang review 2026. bamboo architecture, spa, quiet beach between my khe and hoi an. best couples/honeymoon resort in da nang? review naman retreat da nang'},
  {t:'Ba Na Hills 2026: Is It Worth It? Honest Visitor Guide',u:'ba-na-hills-guide.html',c:'Attractions',e:'Honest Ba Na Hills guide for 2026. The Golden Bridge, what it',p:72,k:'ba na hills golden bridge cable car theme park french village sun world day trip ba na hills 2026: is it worth it? honest visitor guide honest ba na hills guide for 2026. the golden bridge, what it ba na hills guide'},
  {t:'Best Hotels Near My Khe Beach Da Nang 2026 — Local Area Guide',u:'best-hotels-near-my-khe-beach.html',c:'Beach & Coastal',e:'The best hotels near My Khe Beach in Da Nang 2026. Which stretch to stay on, what',p:72,k:'best hotels near my khe beach da nang 2026 — local area guide the best hotels near my khe beach in da nang 2026. which stretch to stay on, what best hotels near my khe beach'},
  {t:'TIA Wellness Resort Da Nang — Full Review 2026',u:'review-tia-wellness-resort-da-nang.html',c:'Hotel Review',e:'Full TIA Wellness Resort Da Nang review 2026. Adults-only, all-inclusive spa resort on My Khe. Best couples and wellness retreat in Da Nang? Honest assessment.',p:71,k:'tia wellness resort da nang — full review 2026 full tia wellness resort da nang review 2026. adults-only, all-inclusive spa resort on my khe. best couples and wellness retreat in da nang? honest assessment. review tia wellness resort da nang'},
  {t:'A La Carte Da Nang Beach — Full Review 2026',u:'review-a-la-carte-da-nang.html',c:'Hotel Review',e:'Full A La Carte Da Nang review 2026. Best value on My Khe Beach — rooftop infinity pool bar, apartment-style rooms from $70/night. Worth booking?',p:70,k:'a la carte da nang beach — full review 2026 full a la carte da nang review 2026. best value on my khe beach — rooftop infinity pool bar, apartment-style rooms from $70/night. worth booking? review a la carte da nang'},
  {t:'Son Tra Peninsula Da Nang: Complete Guide 2026',u:'son-tra-peninsula-da-nang.html',c:'Attractions',e:'Son Tra Peninsula Da Nang guide 2026, Monkey Mountain, Lady Buddha, hidden beaches, and the best resort hotels. Everything to know before you visit.',p:70,k:'son tra peninsula monkey mountain viewpoint nature hiking beach quiet son tra peninsula da nang: complete guide 2026 son tra peninsula da nang guide 2026, monkey mountain, lady buddha, hidden beaches, and the best resort hotels. everything to know before you visit. son tra peninsula da nang'},
  {t:'Best Han River Hotels in Da Nang 2026 — Views, Location, Honest Picks',u:'best-han-river-hotels-da-nang.html',c:'Attractions',e:'Best hotels on the Han River in Da Nang 2026. Dragon Bridge views, city walkability, rooftop bars, and why some travelers prefer the river over the beach.',p:70,k:'best han river hotels in da nang 2026 — views, location, honest picks best hotels on the han river in da nang 2026. dragon bridge views, city walkability, rooftop bars, and why some travelers prefer the river over the beach. best han river hotels da nang'},
  {t:'Novotel Da Nang Han River — Full Review 2026',u:'review-novotel-da-nang-han-river.html',c:'Hotel Review',e:'Full Novotel Da Nang Premier Han River review. Best Dragon Bridge views, Sky36 rooftop bar, city-centre location. Worth the premium? Honest verdict.',p:69,k:'novotel da nang han river — full review 2026 full novotel da nang premier han river review. best dragon bridge views, sky36 rooftop bar, city-centre location. worth the premium? honest verdict. review novotel da nang han river'},
  {t:'Pullman Da Nang Beach Resort — Full Review 2026',u:'review-pullman-da-nang.html',c:'Hotel Review',e:'Full Pullman Da Nang Beach Resort review 2026. Northern My Khe, large pool, quieter stretch of beach. Strong mid-luxury choice at competitive rates.',p:68,k:'pullman da nang beach resort — full review 2026 full pullman da nang beach resort review 2026. northern my khe, large pool, quieter stretch of beach. strong mid-luxury choice at competitive rates. review pullman da nang'},
  {t:'Best Resorts on Son Tra Peninsula Da Nang 2026',u:'best-resorts-son-tra-peninsula.html',c:'Attractions',e:'The best resorts on Son Tra Peninsula for 2026, InterContinental, Premier Village, and Naman Retreat compared. Clifftop villas from $200/night.',p:68,k:'best resorts on son tra peninsula da nang 2026 the best resorts on son tra peninsula for 2026, intercontinental, premier village, and naman retreat compared. clifftop villas from $200/night. best resorts son tra peninsula'},
  {t:'InterContinental vs Hyatt Da Nang 2026 — Which to Book?',u:'intercontinental-vs-hyatt-da-nang.html',c:'Comparison',e:'InterContinental Sun Peninsula vs Hyatt Regency Da Nang: honest comparison of location, pools, value, and who each resort suits. Local verdict included.',p:67,k:'intercontinental vs hyatt comparison which better sun peninsula non nuoc intercontinental vs hyatt da nang 2026 — which to book? intercontinental sun peninsula vs hyatt regency da nang: honest comparison of location, pools, value, and who each resort suits. local verdict included. intercontinental v'},
  {t:'Best Honeymoon Hotels in Da Nang 2026 — Romantic Picks',u:'da-nang-honeymoon-hotels.html',c:'Romance & Couples',e:'Best honeymoon hotels in Da Nang 2026. InterContinental Sun Peninsula, Naman Retreat, TIA Wellness, and romantic resorts with privacy, spa access, and beach views.',p:67,k:'honeymoon romantic couples villas spa private pool sunset best honeymoon hotels in da nang 2026 — romantic picks best honeymoon hotels in da nang 2026. intercontinental sun peninsula, naman retreat, tia wellness, and romantic resorts with privacy, spa access, and beach views. da nang honeymoon hotel'},
  {t:'Best Family Resort in Da Nang 2026 — Honest Picks by a Local',u:'best-family-resort-da-nang.html',c:'Family Hotels',e:'The best family resorts in Da Nang for 2026. Hyatt Regency, Sheraton Grand, Mikazuki — kids clubs, pools, beach safety and value all assessed honestly.',p:66,k:'best family resort in da nang 2026 — honest picks by a local the best family resorts in da nang for 2026. hyatt regency, sheraton grand, mikazuki — kids clubs, pools, beach safety and value all assessed honestly. best family resort da nang'},
  {t:'Han River Night Cruise Da Nang 2026, Dragon Bridge',u:'han-river-night-cruise-da-nang.html',c:'Attractions',e:'Han River night cruise Da Nang guide 2026. Prices from $12, dock locations, Dragon Bridge views, and whether the cruise is actually worth booking. Honest verdict.',p:65,k:'han river cruise boat night cruise dragon bridge riverside dinner han river night cruise da nang 2026, dragon bridge han river night cruise da nang guide 2026. prices from $12, dock locations, dragon bridge views, and whether the cruise is actually worth booking. honest verdict. han river night crui'},
  {t:'InterContinental vs Furama Da Nang 2026 — Which Luxury Resort?',u:'intercontinental-vs-furama-da-nang.html',c:'Comparison',e:'InterContinental Sun Peninsula vs Furama Resort Da Nang: dramatic clifftop seclusion vs mature garden luxury. Which suits your trip? Local verdict.',p:65,k:'intercontinental vs furama comparison luxury intercontinental vs furama da nang 2026 — which luxury resort? intercontinental sun peninsula vs furama resort da nang: dramatic clifftop seclusion vs mature garden luxury. which suits your trip? local verdict. intercontinental vs furama da nang'},
  {t:'Best Luxury Resort for Couples in Da Nang 2026 — Local Picks',u:'best-luxury-resort-couples-da-nang.html',c:'Romance & Couples',e:'The best luxury resorts for couples in Da Nang in 2026. InterContinental, Naman Retreat, TIA Wellness, Fusion Maia — ranked by a local who knows them all.',p:65,k:'couples romantic luxury villas private spa honeymoon best luxury resort for couples in da nang 2026 — local picks the best luxury resorts for couples in da nang in 2026. intercontinental, naman retreat, tia wellness, fusion maia — ranked by a local who knows them all. best luxury resort couples da n'},
  {t:'Da Nang Airport Guide 2026, Arrivals, Grab & Tips',u:'da-nang-airport-guide.html',c:'Transport',e:'Da Nang Airport (DAD) guide for 2026. Grab costs $4–5, taxis $5–7, avoid overcharging. Arrivals, departures, and the fastest way into the city.',p:65,k:'airport DAD arrivals departures grab taxi transfer getting to city da nang airport da nang airport guide 2026, arrivals, grab & tips da nang airport (dad) guide for 2026. grab costs $4–5, taxis $5–7, avoid overcharging. arrivals, departures, and the fastest way into the city. da nang airport guide'},
  {t:'Best Cafes in Da Nang 2026 — An Thuong & Beyond',u:'best-cafes-da-nang.html',c:'Dining & Food',e:'The best cafes in Da Nang in 2026: specialty coffee, working cafes, rooftop spots, and local favourites in An Thuong and across the city. Local picks only.',p:65,k:'cafes coffee cafe brunch work cafe specialty coffee an thuong best cafes in da nang 2026 — an thuong & beyond the best cafes in da nang in 2026: specialty coffee, working cafes, rooftop spots, and local favourites in an thuong and across the city. local picks only. best cafes da nang'},
  {t:'Da Nang with Kids — Complete Family Travel Guide 2026',u:'da-nang-with-kids-guide.html',c:'Family Travel',e:'Da Nang with kids in 2026. Beach safety, family resorts, kids clubs, activities, food, transport, and honest advice for families with children.',p:64,k:'kids children family activities ba na hills waterpark beach da nang with kids — complete family travel guide 2026 da nang with kids in 2026. beach safety, family resorts, kids clubs, activities, food, transport, and honest advice for families with children. da nang with kids guide'},
  {t:'Novotel vs Hilton Da Nang 2026 — Han River Hotel Showdown',u:'novotel-vs-hilton-da-nang.html',c:'Comparison',e:'Novotel Han River vs Hilton Da Nang: the two best city-centre hotels compared honestly. Dragon Bridge views, rooftop bars, value — which wins in 2026?',p:63,k:'novotel vs hilton comparison han river city novotel vs hilton da nang 2026 — han river hotel showdown novotel han river vs hilton da nang: the two best city-centre hotels compared honestly. dragon bridge views, rooftop bars, value — which wins in 2026? novotel vs hilton da nang'},
  {t:'Da Nang Travel Guides 2026, Hotels & Neighbourhoods',u:'guides.html',c:'Travel Guide',e:'Complete Da Nang travel guides for 2026, best hotels by area, where to stay, weather, dining, and practical tips. All updated by a local expat.',p:63,k:'da nang travel guides 2026, hotels & neighbourhoods complete da nang travel guides for 2026, best hotels by area, where to stay, weather, dining, and practical tips. all updated by a local expat. guides'},
  {t:'TIA Wellness vs Naman Retreat Da Nang 2026 — Spa Resort Compared',u:'tia-wellness-vs-naman-retreat-da-nang.html',c:'Comparison',e:'TIA Wellness Resort vs Naman Retreat Da Nang: the two best wellness resorts in central Vietnam. Pricing, spa quality, beach, villas compared by a local.',p:62,k:'tia wellness naman retreat spa comparison wellness couples tia wellness vs naman retreat da nang 2026 — spa resort compared tia wellness resort vs naman retreat da nang: the two best wellness resorts in central vietnam. pricing, spa quality, beach, villas compared by a local. tia wellness vs naman r'},
  {t:'All Hotels in Da Nang 2026, By Area & Category',u:'hotels.html',c:'Hotels Hub',e:'Browse every hotel category in Da Nang for 2026, luxury resorts, beach hotels, boutique stays, and family picks. 110+ properties reviewed by area.',p:62,k:'all hotels in da nang 2026, by area & category browse every hotel category in da nang for 2026, luxury resorts, beach hotels, boutique stays, and family picks. 110+ properties reviewed by area. hotels'},
  {t:'Da Nang Airport to Hoi An, Transport Guide 2026',u:'da-nang-airport-to-hoi-an.html',c:'Transport',e:'How to get from Da Nang Airport to Hoi An in 2026, Grab, private car, taxi, and shuttle options compared. Real costs, timings, and practical tips for every traveller.',p:62,k:'airport to hoi an transfer taxi bus shuttle transport da nang airport to hoi an, transport guide 2026 how to get from da nang airport to hoi an in 2026, grab, private car, taxi, and shuttle options compared. real costs, timings, and practical tips for every traveller. da nang airport to hoi an'},
  {t:'Beachfront vs City Hotels in Da Nang — Which Is Right for You?',u:'beachfront-vs-city-hotels-da-nang.html',c:'Comparison',e:'Should you stay at a beachfront hotel or a city hotel in Da Nang? Honest comparison of My Khe/Non Nuoc beach hotels vs Han River city hotels with clear verdicts by traveler type.',p:61,k:'beachfront vs city hotels comparison my khe han river which better beachfront vs city hotels in da nang — which is right for you? should you stay at a beachfront hotel or a city hotel in da nang? honest comparison of my khe/non nuoc beach hotels vs han river city hotels with clear verdicts by travel'},
  {t:'Da Nang Hotel Reviews 2026, Honest Independent Ratings',u:'hotel-reviews.html',c:'Hotel Reviews',e:'Honest, independent reviews of 24 Da Nang hotels for 2026. Local expat perspective, no sponsored content. InterContinental to budget beach hotels.',p:61,k:'da nang hotel reviews 2026, honest independent ratings honest, independent reviews of 24 da nang hotels for 2026. local expat perspective, no sponsored content. intercontinental to budget beach hotels. hotel reviews'},
  {t:'Da Nang 5-Day Itinerary 2026 — The Complete Plan',u:'da-nang-5-day-itinerary.html',c:'Itinerary',e:'The ideal 5-day Da Nang itinerary for 2026. Cover the beach, day trips to Hoi An and Hue, Ba Na Hills, and the city without rushing.',p:60,k:'da nang 5-day itinerary 2026 — the complete plan the ideal 5-day da nang itinerary for 2026. cover the beach, day trips to hoi an and hue, ba na hills, and the city without rushing. da nang 5 day itinerary'},
  {t:'Best Night Markets in Da Nang 2026 — Han Market, Con Market, and Beyond',u:'best-night-markets-da-nang.html',c:'Dining & Food',e:'Best night markets in Da Nang 2026. Con Market, Son Tra Night Market, An Thuong food strip, Han Market, helipad area - hours, what to buy, what to avoid, negotiation tips.',p:60,k:'night market street food markets con market han market best night markets in da nang 2026 — han market, con market, and beyond best night markets in da nang 2026. con market, son tra night market, an thuong food strip, han market, helipad area - hours, what to buy, what to avoid, negotiation tips. b'},
  {t:'7 Days in Da Nang & Hoi An: Itinerary Guide 2026',u:'da-nang-7-day-itinerary.html',c:'Itinerary',e:'The best 7-day Da Nang itinerary for 2026, day-by-day plans for beach, Ba Na Hills, Marble Mountains, Son Tra, Hoi An, and Hue. Make every day count.',p:59,k:'7 days in da nang & hoi an: itinerary guide 2026 the best 7-day da nang itinerary for 2026, day-by-day plans for beach, ba na hills, marble mountains, son tra, hoi an, and hue. make every day count. da nang 7 day itinerary'},
  {t:'Best Hotels for Da Nang Fireworks Festival 2026 (DIFF)',u:'da-nang-fireworks-festival-hotels.html',c:'Events',e:'Best hotels to watch DIFF 2026 fireworks from Da Nang. Dragon Bridge view rooms, riverside towers, rooftop bars — book early, prices spike in June.',p:58,k:'fireworks DIFF festival dragon bridge riverside festival june best hotels for da nang fireworks festival 2026 (diff) best hotels to watch diff 2026 fireworks from da nang. dragon bridge view rooms, riverside towers, rooftop bars — book early, prices spike in june. da nang fireworks festival hotels'},
  {t:'Da Nang Hotels with Rooftop Pool 2026 — Best Views Ranked',u:'da-nang-hotels-rooftop-pool.html',c:'Hotel Features',e:'Best Da Nang hotels with rooftop pools in 2026. A La Carte, Azura, Brilliant Hotel, Wyndham Soleil — ranked for views, pool quality, and value.',p:58,k:'rooftop pool infinity pool views sky pool hotel amenities da nang hotels with rooftop pool 2026 — best views ranked best da nang hotels with rooftop pools in 2026. a la carte, azura, brilliant hotel, wyndham soleil — ranked for views, pool quality, and value. da nang hotels rooftop pool'},
  {t:'Best Hotels in An Thuong Da Nang 2026 — The Neighborhood Guide',u:'best-hotels-an-thuong-da-nang.html',c:'Guide',e:'An Thuong is Da Nang',p:58,k:'an thuong neighbourhood expat area boutique cafes restaurants best hotels in an thuong da nang 2026 — the neighborhood guide an thuong is da nang best hotels an thuong da nang'},
  {t:'Da Nang Hotels with Spa Packages 2026 — All-Inclusive and Day Spa Picks',u:'da-nang-hotels-spa-packages.html',c:'Hotel Features',e:'Best spa hotels in Da Nang 2026. TIA Wellness all-inclusive spa, Naman Spa at Naman Retreat, Fusion Maia daily treatments — compared honestly for couples and wellness travelers.',p:56,k:'spa wellness packages massage treatment da nang hotels with spa packages 2026 — all-inclusive and day spa picks best spa hotels in da nang 2026. tia wellness all-inclusive spa, naman spa at naman retreat, fusion maia daily treatments — compared honestly for couples and wellness travelers. da nang ho'},
  {t:'Da Nang & Hoi An Markets Guide 2026, What to Buy',u:'da-nang-hoi-an-markets-guide.html',c:'Dining & Food',e:'Da Nang and Hoi An markets guide 2026, Han Market vs Con Market, Hoi An Night Market, what to buy, bargaining advice, and what to avoid. Local guide.',p:55,k:'markets hoi an da nang shopping street food lanterns da nang & hoi an markets guide 2026, what to buy da nang and hoi an markets guide 2026, han market vs con market, hoi an night market, what to buy, bargaining advice, and what to avoid. local guide. da nang hoi an markets guide'},
  {t:'Da Nang Hotels with Infinity Pools 2026 — Best Views Ranked',u:'da-nang-hotels-infinity-pool.html',c:'Hotel Features',e:'Best infinity pool hotels in Da Nang 2026. InterContinental',p:55,k:'infinity pool pool view ocean view rooftop swimming da nang hotels with infinity pools 2026 — best views ranked best infinity pool hotels in da nang 2026. intercontinental da nang hotels infinity pool'},
  {t:'Adults-Only Hotels in Da Nang 2026 — No Kids, No Noise',u:'da-nang-adults-only-hotels.html',c:'Romance & Couples',e:'The best adults-only hotels and resorts in Da Nang for 2026. TIA Wellness, Naman Retreat, Melia, and options that deliver genuine peace and quiet.',p:55,k:'adults only couples quiet romantic adults-only hotels in da nang 2026 — no kids, no noise the best adults-only hotels and resorts in da nang for 2026. tia wellness, naman retreat, melia, and options that deliver genuine peace and quiet. da nang adults only hotels'},
  {t:'Best Riverside Hotels in Da Nang 2026, Han River Views',u:'da-nang-riverfront-hotels.html',c:'Guide',e:'Best Han River hotels in Da Nang for 2026, rooftop pool views of Dragon Bridge, central location. Top city hotel picks from $60/night.',p:55,k:'riverfront han river views hotels city centre best riverside hotels in da nang 2026, han river views best han river hotels in da nang for 2026, rooftop pool views of dragon bridge, central location. top city hotel picks from $60/night. da nang riverfront hotels'},
  {t:'Da Nang Hotels with Lazy River &amp; Water Parks 2026',u:'da-nang-hotels-with-lazy-river.html',c:'Hotel Features',e:'Da Nang hotels with lazy rivers and water parks in 2026. Hyatt Regency, Sheraton Grand, Mikazuki — which have the best water facilities for families.',p:54,k:'lazy river water park kids family Sheraton Hyatt da nang hotels with lazy river &amp; water parks 2026 da nang hotels with lazy rivers and water parks in 2026. hyatt regency, sheraton grand, mikazuki — which have the best water facilities for families. da nang hotels with lazy river'},
  {t:'Da Nang Hotels with Private Pool Villas 2026 — Honest Picks',u:'da-nang-hotels-private-pool-villa.html',c:'Hotel Features',e:'Hotels and resorts with private pool villas in Da Nang 2026. Naman Retreat, Premier Village, InterContinental, TIA Wellness — what you actually get at each price point.',p:53,k:'private pool villa romantic couples honeymoon luxury da nang hotels with private pool villas 2026 — honest picks hotels and resorts with private pool villas in da nang 2026. naman retreat, premier village, intercontinental, tia wellness — what you actually get at each price point. da nang hotels pri'},
  {t:'Best Hotel Breakfast in Da Nang 2026 — Worth the Upgrade?',u:'best-resort-breakfast-da-nang.html',c:'Dining & Food',e:'Which Da Nang hotels have the best breakfast spreads in 2026? InterContinental, Hyatt Regency, Sheraton, Naman Retreat reviewed honestly. Is breakfast included worth it?',p:52,k:'breakfast buffet best resort morning meal best hotel breakfast in da nang 2026 — worth the upgrade? which da nang hotels have the best breakfast spreads in 2026? intercontinental, hyatt regency, sheraton, naman retreat reviewed honestly. is breakfast included worth it? best resort breakfast da nang'},
  {t:'Da Nang Hotels with Connecting Rooms 2026 — For Families and Groups',u:'da-nang-hotels-connecting-rooms.html',c:'Hotel Features',e:'Which Da Nang hotels have connecting rooms or family suites in 2026? Sheraton Grand, Hyatt Regency, Furama, and others with honest room configuration details.',p:52,k:'connecting rooms family kids adjacent rooms family suite da nang hotels with connecting rooms 2026 — for families and groups which da nang hotels have connecting rooms or family suites in 2026? sheraton grand, hyatt regency, furama, and others with honest room configuration details. da nang hotels c'},
  {t:'Best Areas in Da Nang for Families 2026 — Where to Stay with Kids',u:'best-areas-da-nang-families.html',c:'Family Travel',e:'Where to stay in Da Nang with kids in 2026. Non Nuoc vs My Khe for families, resort vs city hotel, and the honest pros and cons of each area with children.',p:52,k:'family areas non nuoc my khe kids pools best areas in da nang for families 2026 — where to stay with kids where to stay in da nang with kids in 2026. non nuoc vs my khe for families, resort vs city hotel, and the honest pros and cons of each area with children. best areas da nang families'},
  {t:'An Bang Beach Hotels Hoi An 2026, Best Stays Near the Beach',u:'an-bang-beach-hotels.html',c:'Hoi An',e:'The best hotels near An Bang Beach in Hoi An for 2026. Beach conditions, transport to Old Town, and honest hotel picks for An Bang and nearby Cua Dai.',p:50,k:'an bang beach hoi an beach hotels cua dai an bang beach hotels hoi an 2026, best stays near the beach the best hotels near an bang beach in hoi an for 2026. beach conditions, transport to old town, and honest hotel picks for an bang and nearby cua dai. an bang beach hotels'},
  {t:'Best Value Hotels in Hoi An 2026, Most for Your Money',u:'best-value-hotels-hoi-an.html',c:'Hoi An',e:'The best value hotels in Hoi An for 2026, boutique pools, great locations, and genuine comfort without paying luxury rates. Honest picks from $45/night.',p:48,k:'hoi an budget value cheap affordable hotels best value hotels in hoi an 2026, most for your money the best value hotels in hoi an for 2026, boutique pools, great locations, and genuine comfort without paying luxury rates. honest picks from $45/night. best value hotels hoi an'},
  {t:'Da Nang vs Hanoi 2026, Beach vs Capital City?',u:'da-nang-vs-hanoi.html',c:'Comparison',e:'Da Nang vs Hanoi compared for 2026, coast vs capital, costs, families, Old Quarter vs My Khe Beach, and weather. Clear verdict for your Vietnam itinerary.',p:48,k:'da nang vs hanoi comparison north south vietnam da nang vs hanoi 2026, beach vs capital city? da nang vs hanoi compared for 2026, coast vs capital, costs, families, old quarter vs my khe beach, and weather. clear verdict for your vietnam itinerary. da nang vs hanoi'},
  {t:'Da Nang vs Ho Chi Minh City 2026, Which to Visit?',u:'da-nang-vs-ho-chi-minh-city.html',c:'Comparison',e:'Da Nang vs Ho Chi Minh City compared for 2026, beach vs city energy, costs, food, families, nightlife. Which Vietnam destination is right for your trip?',p:47,k:'da nang vs ho chi minh saigon comparison vietnam da nang vs ho chi minh city 2026, which to visit? da nang vs ho chi minh city compared for 2026, beach vs city energy, costs, food, families, nightlife. which vietnam destination is right for your trip? da nang vs ho chi minh city'},
  {t:'Da Nang vs Phuket: Which Beach Destination? (2026)',u:'da-nang-vs-phuket.html',c:'Comparison',e:'Da Nang vs Phuket 2026 comparison. Beaches, hotels, costs, weather, families, couples, and digital nomads. Which is better for your trip?',p:46,k:'da nang vs phuket comparison thailand beach da nang vs phuket: which beach destination? (2026) da nang vs phuket 2026 comparison. beaches, hotels, costs, weather, families, couples, and digital nomads. which is better for your trip? da nang vs phuket'},
  {t:'Is Hoi An Cheaper Than Da Nang?, Honest 2026 Cost Comparison',u:'is-hoi-an-cheaper-than-da-nang.html',c:'Hoi An',e:'Is Hoi An cheaper than Da Nang in 2026? Honest comparison of hotels, food, transport, and daily costs to help you decide where to stay and how to budget.',p:45,k:'hoi an da nang cheaper budget cost comparison is hoi an cheaper than da nang?, honest 2026 cost comparison is hoi an cheaper than da nang in 2026? honest comparison of hotels, food, transport, and daily costs to help you decide where to stay and how to budget. is hoi an cheaper than da nang'},
  {t:'Hyatt Regency Da Nang Review 2026 — Is It Worth It?',u:'hyatt-regency-da-nang.html',c:'Guide',e:'Hyatt Regency Da Nang review 2026: 6 pools, lazy river, Non Nuoc beachfront. Best for families. Honest assessment of what it delivers vs the price.',p:45,k:'hyatt regency da nang review 2026 — is it worth it? hyatt regency da nang review 2026: 6 pools, lazy river, non nuoc beachfront. best for families. honest assessment of what it delivers vs the price. hyatt regency da nang'},
  {t:'InterContinental Danang Sun Peninsula Review 2026',u:'intercontinental-da-nang.html',c:'Guide',e:'Honest InterContinental Danang review from a local: Bill Bensley',p:45,k:'intercontinental danang sun peninsula review 2026 honest intercontinental danang review from a local: bill bensley intercontinental da nang'},
  {t:'Da Nang Hotel Prices by Month: Cheapest and Most Expensive Times to Visit',u:'da-nang-hotel-prices-by-month.html',c:'Budget & Costs',e:'Compare Da Nang hotel prices month by month, beach season, rainy season, fireworks season, and the best-value times to book.',p:44,k:'hotel prices by month cheapest when to book rates peak season da nang hotel prices by month: cheapest and most expensive times to visit compare da nang hotel prices month by month, beach season, rainy season, fireworks season, and the best-value times to book. da nang hotel prices by month'},
  {t:'Sheraton Grand Da Nang Review 2026 — Best Family Resort?',u:'sheraton-grand-da-nang.html',c:'Guide',e:'Sheraton Grand Da Nang 2026: Da Nang',p:44,k:'sheraton grand da nang review 2026 — best family resort? sheraton grand da nang 2026: da nang sheraton grand da nang'},
  {t:'Da Nang Hotel Prices: What You\'ll Really Pay in 2026',u:'da-nang-hotel-prices.html',c:'Budget & Costs',e:'See what hotels in Da Nang actually cost by area, season, and travel style, from budget beach stays to luxury resorts.',p:43,k:'hotel prices rates how much cost to stay da nang hotel prices: what you\'ll really pay in 2026 see what hotels in da nang actually cost by area, season, and travel style, from budget beach stays to luxury resorts. da nang hotel prices'},
  {t:'Naman Retreat Da Nang Review 2026 — Romantic & Quiet',u:'naman-retreat-da-nang.html',c:'Guide',e:'Naman Retreat Da Nang 2026: the best couples resort between My Khe and Hoi An. Bamboo architecture, spa, quiet beach. Honest review from a local.',p:43,k:'naman retreat da nang review 2026 — romantic & quiet naman retreat da nang 2026: the best couples resort between my khe and hoi an. bamboo architecture, spa, quiet beach. honest review from a local. naman retreat da nang'},
  {t:'How Many Days in Da Nang? (Honest 2026 Guide)',u:'how-many-days-in-da-nang.html',c:'Guide',e:'How many days do you need in Da Nang? 2, 3, 5, or 7 days - what you can actually do and see in each timeframe. Honest local advice.',p:42,k:'how many days trip length visit duration stay how many days in da nang? (honest 2026 guide) how many days do you need in da nang? 2, 3, 5, or 7 days - what you can actually do and see in each timeframe. honest local advice. how many days in da nang'},
  {t:'15 Mistakes Tourists Make in Da Nang (2026 Advice)',u:'da-nang-travel-mistakes.html',c:'Guide',e:'The 15 most common Da Nang tourist mistakes for 2026, wrong hotel location, Ba Na Hills timing, beach flag errors, taxi scams. A local expat',p:42,k:'mistakes avoid tips common errors first time 15 mistakes tourists make in da nang (2026 advice) the 15 most common da nang tourist mistakes for 2026, wrong hotel location, ba na hills timing, beach flag errors, taxi scams. a local expat da nang travel mistakes'},
  {t:'A La Carte Da Nang Beach Hotel Review (2026)',u:'a-la-carte-da-nang.html',c:'Guide',e:'A La Carte Da Nang review 2026: best overall value on My Khe Beach, rooftop infinity pool bar, apartment-style rooms. From $70/night. Full honest review.',p:42,k:'a la carte da nang beach hotel review (2026) a la carte da nang review 2026: best overall value on my khe beach, rooftop infinity pool bar, apartment-style rooms. from $70/night. full honest review. a la carte da nang'},
  {t:'Pullman Da Nang Beach Resort Review 2026',u:'pullman-da-nang.html',c:'Guide',e:'Pullman Da Nang Beach Resort 2026: northern My Khe, large pool, quieter stretch of beach. Honest review — who it',p:42,k:'pullman da nang beach resort review 2026 pullman da nang beach resort 2026: northern my khe, large pool, quieter stretch of beach. honest review — who it pullman da nang'},
  {t:'10 Da Nang Tourist Mistakes (What Most Visitors Get Wrong)',u:'da-nang-tourist-mistakes.html',c:'Guide',e:'The 10 most common mistakes tourists make in Da Nang — hotel location, beach conditions, transport, food, and timing mistakes that ruin trips.',p:41,k:'tourist mistakes avoid tips advice 10 da nang tourist mistakes (what most visitors get wrong) the 10 most common mistakes tourists make in da nang — hotel location, beach conditions, transport, food, and timing mistakes that ruin trips. da nang tourist mistakes'},
  {t:'Novotel Danang Premier Han River Review (2026)',u:'novotel-da-nang-han-river.html',c:'Attractions',e:'Novotel Danang Premier Han River review 2026: best-value city hotel in Da Nang. Rooftop pool, Dragon Bridge views, from $75/night. Is it worth booking?',p:41,k:'novotel danang premier han river review (2026) novotel danang premier han river review 2026: best-value city hotel in da nang. rooftop pool, dragon bridge views, from $75/night. is it worth booking? novotel da nang han river'},
  {t:'Da Nang Malls Guide: Best Shopping Centers Near Da Nang Hotels',u:'da-nang-malls-guide.html',c:'Shopping',e:'Find the best malls and shopping centers in Da Nang, plus which hotel areas are most convenient for shopping, dining, and rainy days.',p:40,k:'shopping mall vincom big c lotte mart retail da nang malls guide: best shopping centers near da nang hotels find the best malls and shopping centers in da nang, plus which hotel areas are most convenient for shopping, dining, and rainy days. da nang malls guide'},
  {t:'Best Shopping in Da Nang 2026 — Markets, Malls, and What to Buy',u:'best-shopping-da-nang.html',c:'Shopping',e:'Best shopping in Da Nang 2026. Con Market and Han Market for tailors and silk, Vincom Plaza, An Thuong boutiques, local coffee to bring home, custom tailoring process, and what to avoid.',p:40,k:'shopping markets souvenirs lacquer silk an thuong han market best shopping in da nang 2026 — markets, malls, and what to buy best shopping in da nang 2026. con market and han market for tailors and silk, vincom plaza, an thuong boutiques, local coffee to bring home, custom tailoring process, and wha'},
  {t:'Furama Resort Da Nang Review 2026 — Still Worth It?',u:'furama-resort-da-nang.html',c:'Guide',e:'Furama Resort Da Nang 2026: Da Nang',p:40,k:'furama resort my khe luxury beachfront furama resort da nang review 2026 — still worth it? furama resort da nang 2026: da nang furama resort da nang'},
  {t:'Arbora Luxury Collection Da Nang, Opening Guide 2026',u:'arbora-luxury-collection-da-nang.html',c:'Luxury Hotels',e:'Arbora Luxury Collection Resort opening on Non Nuoc Beach in 2026. Location, Bonvoy rates, dining, and what to expect from Da Nang',p:40,k:'arbora marriott luxury collection non nuoc new 2026 arbora luxury collection da nang, opening guide 2026 arbora luxury collection resort opening on non nuoc beach in 2026. location, bonvoy rates, dining, and what to expect from da nang arbora luxury collection da nang'},
  {t:'Fusion Suites Da Nang Review, All-Inclusive? (2026)',u:'fusion-suites-da-nang.html',c:'Guide',e:'Fusion Suites Da Nang review 2026: all-suite beachfront hotel with spa-inclusive daily breakfast. From $95/night, the most unusual value in Da Nang.',p:39,k:'fusion suites beach boutique all inclusive breakfast fusion suites da nang review, all-inclusive? (2026) fusion suites da nang review 2026: all-suite beachfront hotel with spa-inclusive daily breakfast. from $95/night, the most unusual value in da nang. fusion suites da nang'},
  {t:'Da Nang in the Rainy Season — What to Expect (2026)',u:'rainy-season-da-nang-guide.html',c:'Weather',e:'What is Da Nang like during the rainy season? October-December weather reality, what',p:38,k:'rain rainy season typhoon wet when avoid october november da nang in the rainy season — what to expect (2026) what is da nang like during the rainy season? october-december weather reality, what rainy season da nang guide'},
  {t:'Da Nang First-Time Travel Guide 2026 — Everything You Need to Know',u:'da-nang-first-time-travel-guide.html',c:'First-Time Guide',e:'Complete first-timer guide to Da Nang 2026. When to go, where to stay, how to get around, what to eat, top 5 things to do, biggest mistakes, day trips to Hoi An and Ba Na Hills, money and SIM.',p:38,k:'first time travel guide complete overview da nang first-time travel guide 2026 — everything you need to know complete first-timer guide to da nang 2026. when to go, where to stay, how to get around, what to eat, top 5 things to do, biggest mistakes, day trips to hoi an and ba na hills, money and sim'},
  {t:'Hoi An for First-Time Visitors 2026, Complete Guide',u:'hoi-an-first-time-visitors.html',c:'Hoi An',e:'Everything first-time visitors need before arriving in Hoi An, where to stay, Ancient Town reality check, what to eat, tailors, day trips. Honest 2026 guide.',p:38,k:'hoi an first time guide tips visitor hoi an for first-time visitors 2026, complete guide everything first-time visitors need before arriving in hoi an, where to stay, ancient town reality check, what to eat, tailors, day trips. honest 2026 guide. hoi an first time visitors'},
  {t:'Grand Mercure Da Nang Review, Han River Views (2026)',u:'grand-mercure-da-nang.html',c:'Guide',e:'Grand Mercure Da Nang review 2026: spacious suites with Han River views, central location. From $90/night, Accor',p:38,k:'grand mercure accor han river city hotel grand mercure da nang review, han river views (2026) grand mercure da nang review 2026: spacious suites with han river views, central location. from $90/night, accor grand mercure da nang'},
  {t:'Four Points by Sheraton Danang Review (2026)',u:'four-points-sheraton-da-nang.html',c:'Guide',e:'Four Points by Sheraton Danang review 2026: reliable 4-star on My Khe Beach, strong breakfast, from $80/night. Worth it vs better-value alternatives?',p:38,k:'four points sheraton marriott budget value han river four points by sheraton danang review (2026) four points by sheraton danang review 2026: reliable 4-star on my khe beach, strong breakfast, from $80/night. worth it vs better-value alternatives? four points sheraton da nang'},
  {t:'Azura Da Nang Review, Han River Boutique (2026)',u:'azura-da-nang.html',c:'Guide',e:'Azura Da Nang Hotel review 2026: contemporary boutique near the Han River, more character than the big brands for less money. From $65/night. Worth it?',p:37,k:'azura boutique han river character small hotel azura da nang review, han river boutique (2026) azura da nang hotel review 2026: contemporary boutique near the han river, more character than the big brands for less money. from $65/night. worth it? azura da nang'},
  {t:'Brilliant Hotel Da Nang Review, Best Budget Pick? (2026)',u:'brilliant-hotel-da-nang.html',c:'Guide',e:'Brilliant Hotel Da Nang review 2026: best budget option near Dragon Bridge and Han Market. Beachfront location, rooftop pool. From $40/night. Honest rating.',p:36,k:'brilliant hotel han river budget city centre affordable brilliant hotel da nang review, best budget pick? (2026) brilliant hotel da nang review 2026: best budget option near dragon bridge and han market. beachfront location, rooftop pool. from $40/night. honest rating. brilliant hotel da nang'},
  {t:'Living in Da Nang 2026 — Expat Cost of Living & Real Advice',u:'living-in-da-nang-expat-guide.html',c:'Expat & Long Stay',e:'Living in Da Nang as an expat: real costs for 2026, rent, food, healthcare, visas, and what it',p:35,k:'expat living long stay visa cost of living neighbourhoods living in da nang 2026 — expat cost of living & real advice living in da nang as an expat: real costs for 2026, rent, food, healthcare, visas, and what it living in da nang expat guide'},
  {t:'Da Nang with Teenagers, Activities & Hotels (2026)',u:'da-nang-with-teenagers.html',c:'Family Travel',e:'Da Nang with teenagers guide for 2026, Ba Na Hills, surf lessons, watersports, safe beaches, teen-friendly restaurants. Best hotels for teen facilities.',p:35,k:'teenagers teens activities waterpark surfing adventure da nang with teenagers, activities & hotels (2026) da nang with teenagers guide for 2026, ba na hills, surf lessons, watersports, safe beaches, teen-friendly restaurants. best hotels for teen facilities. da nang with teenagers'},
  {t:'Da Nang Travel Budget Guide 2026 — What Everything Costs',u:'da-nang-travel-budget-guide.html',c:'Budget & Costs',e:'Exact costs for a trip to Da Nang in 2026. Daily budgets for backpackers, mid-range, and luxury travellers — accommodation, food, transport, and activities broken down.',p:35,k:'budget travel cheap cost per day spending da nang travel budget guide 2026 — what everything costs exact costs for a trip to da nang in 2026. daily budgets for backpackers, mid-range, and luxury travellers — accommodation, food, transport, and activities broken down. da nang travel budget guide'},
  {t:'How to Live in Da Nang Under $1,000 a Month: Real Cost Guide',u:'how-to-live-in-da-nang-under-1000-a-month.html',c:'Expat & Long Stay',e:'Can you live in Da Nang for under $1,000 a month? This practical local guide breaks down rent, food, transport, cafes, gyms, utilities, and the tradeoffs of budget living in Da Nang.',p:33,k:'cheap cost living budget monthly rent how to live in da nang under $1,000 a month: real cost guide can you live in da nang for under $1,000 a month? this practical local guide breaks down rent, food, transport, cafes, gyms, utilities, and the tradeoffs of budget living in da nang. how to live in da '},
  {t:'Da Nang Travel Guide for Korean Visitors 2026',u:'da-nang-guide-for-korean-travelers.html',c:'Travel Guide',e:'Da Nang guide for Korean travellers 2026: direct flights from Seoul & Busan, Korean restaurants in An Thuong, best beach hotels, and what to do in 5–7 days.',p:33,k:'korean travelers k-town an thuong korean food language da nang travel guide for korean visitors 2026 da nang guide for korean travellers 2026: direct flights from seoul & busan, korean restaurants in an thuong, best beach hotels, and what to do in 5–7 days. da nang guide for korean travelers'},
  {t:'Best Da Nang Beach Hotels Under $100 (2026) — Honest Picks',u:'best-beach-hotel-under-100-da-nang.html',c:'Beach & Coastal',e:'Da Nang beach hotels under $100 per night in 2026. A La Carte, Fusion Suites, Muong Thanh — what you actually get at this price point. No fluff.',p:30,k:'best da nang beach hotels under $100 (2026) — honest picks da nang beach hotels under $100 per night in 2026. a la carte, fusion suites, muong thanh — what you actually get at this price point. no fluff. best beach hotel under 100 da nang'},
  {t:'Da Nang Airport to My Khe Beach — Getting There (2026)',u:'da-nang-airport-to-my-khe.html',c:'Transport Guide',e:'How to get from Da Nang airport to My Khe Beach 2026. Grab, taxi, and transfer options with current prices and travel times.',p:30,k:'da nang airport to my khe beach — getting there (2026) how to get from da nang airport to my khe beach 2026. grab, taxi, and transfer options with current prices and travel times. da nang airport to my khe'},
  {t:'Da Nang Fireworks Festival 2026 (DIFF), Dates & Guide',u:'da-nang-fireworks-festival-diff-2026.html',c:'Events Guide',e:'DIFF 2026 returns May 30 – July 11 with 10 international teams and Sky AR technology. Dates, ticket prices, and what to expect from Da Nang',p:30,k:'da nang fireworks festival 2026 (diff), dates & guide diff 2026 returns may 30 – july 11 with 10 international teams and sky ar technology. dates, ticket prices, and what to expect from da nang da nang fireworks festival diff 2026'},
  {t:'Da Nang Fireworks Festival 2026 — Complete DIFF Guide',u:'da-nang-fireworks-festival-guide.html',c:'Travel Guide',e:'Everything about DIFF 2026: dates, best viewing spots, how to get tickets, where to stay, and what it',p:30,k:'da nang fireworks festival 2026 — complete diff guide everything about diff 2026: dates, best viewing spots, how to get tickets, where to stay, and what it da nang fireworks festival guide'},
  {t:'Best Area to Stay in Da Nang for First-Time Visitors 2026',u:'da-nang-first-time-visitors-area-guide.html',c:'Area Guide',e:'Where should first-time visitors to Da Nang stay? Central My Khe Beach is the answer. Here',p:30,k:'best area to stay in da nang for first-time visitors 2026 where should first-time visitors to da nang stay? central my khe beach is the answer. here da nang first time visitors area guide'},
  {t:'Da Nang Grab Guide 2026 — Prices, Tips, and How It Works',u:'da-nang-grab-guide.html',c:'Transport Guide',e:'Everything you need to know about using Grab in Da Nang 2026. Prices, how to book, airport rides, tips, and when to take a taxi instead.',p:30,k:'da nang grab guide 2026 — prices, tips, and how it works everything you need to know about using grab in da nang 2026. prices, how to book, airport rides, tips, and when to take a taxi instead. da nang grab guide'},
  {t:'Da Nang Grocery Store Guide 2026: Where to Shop, Save, and Stock Up',u:'da-nang-grocery-store-guide.html',c:'Travel Guide',e:'The best grocery stores in Da Nang 2026, Full Market, Jollymart, Winmart, Moonmilk, MegaMart, and Lotte Mart compared. Fresh produce, imported goods, bulk buying, and expat tips.',p:30,k:'da nang grocery store guide 2026: where to shop, save, and stock up the best grocery stores in da nang 2026, full market, jollymart, winmart, moonmilk, megamart, and lotte mart compared. fresh produce, imported goods, bulk buying, and expat tips. da nang grocery store guide'},
  {t:'Da Nang Guide for Australians 2026, Flights & Tips',u:'da-nang-guide-for-australian-travelers.html',c:'Travel Guide',e:'Complete Da Nang guide for Australians in 2026, flights from Sydney, Melbourne & Brisbane, costs in AUD, visa requirements, and the best hotels to book.',p:30,k:'da nang guide for australians 2026, flights & tips complete da nang guide for australians in 2026, flights from sydney, melbourne & brisbane, costs in aud, visa requirements, and the best hotels to book. da nang guide for australian travelers'},
  {t:'Da Nang Travel Guide for Russian Visitors 2026',u:'da-nang-guide-for-russian-travelers.html',c:'Travel Guide',e:'Da Nang guide for Russian tourists 2026, direct flights from Moscow, budget hotels, costs, beaches, visa info, and top things to do. Updated April 2026.',p:30,k:'da nang travel guide for russian visitors 2026 da nang guide for russian tourists 2026, direct flights from moscow, budget hotels, costs, beaches, visa info, and top things to do. updated april 2026. da nang guide for russian travelers'},
  {t:'Da Nang Hotels with Kids Clubs 2026 — Ranked for Families',u:'da-nang-hotels-kids-club.html',c:'Family Travel',e:'Which Da Nang hotels have the best kids clubs in 2026? Hyatt Regency, Sheraton Grand, Furama, and Mikazuki compared honestly for age ranges, hours, and what',p:30,k:'da nang hotels with kids clubs 2026 — ranked for families which da nang hotels have the best kids clubs in 2026? hyatt regency, sheraton grand, furama, and mikazuki compared honestly for age ranges, hours, and what da nang hotels kids club'},
  {t:'Da Nang Hotels Map 2026, Find Hotels by Location',u:'da-nang-hotels-map.html',c:'Area Guide',e:'Interactive Da Nang hotel map for 2026, browse hotels by neighbourhood: My Khe Beach, Han River, Son Tra, and Non Nuoc. Find the right area fast.',p:30,k:'da nang hotels map 2026, find hotels by location interactive da nang hotel map for 2026, browse hotels by neighbourhood: my khe beach, han river, son tra, and non nuoc. find the right area fast. da nang hotels map'},
  {t:'Hotels Near Da Nang Airport 2026 — What to Actually Know',u:'da-nang-hotels-near-airport.html',c:'Transport Guide',e:'Hotels near Da Nang Airport in 2026. The airport is central — most city hotels are 10-15 minutes away. Which ones are closest and what that actually means.',p:30,k:'hotels near da nang airport 2026 — what to actually know hotels near da nang airport in 2026. the airport is central — most city hotels are 10-15 minutes away. which ones are closest and what that actually means. da nang hotels near airport'},
  {t:'Da Nang Hotels with Private Beach 2026 — Which Really Has One?',u:'da-nang-hotels-private-beach.html',c:'Beach & Coastal',e:'Which Da Nang hotels actually have a private beach in 2026? The honest answer is complicated. This guide explains what private beach means here and which hotels deliver.',p:30,k:'da nang hotels with private beach 2026 — which really has one? which da nang hotels actually have a private beach in 2026? the honest answer is complicated. this guide explains what private beach means here and which hotels deliver. da nang hotels private beach'},
  {t:'Da Nang Money Exchange Guide 2026 — ATMs, Cash, and Where to Exchange',u:'da-nang-money-exchange-guide.html',c:'Travel Guide',e:'Where to exchange money in Da Nang 2026. Best rates at gold shops on Hung Vuong St, ATM fees, cash vs card, VND denominations, airport exchange vs city, and tipping norms.',p:30,k:'da nang money exchange guide 2026 — atms, cash, and where to exchange where to exchange money in da nang 2026. best rates at gold shops on hung vuong st, atm fees, cash vs card, vnd denominations, airport exchange vs city, and tipping norms. da nang money exchange guide'},
  {t:'Quietest Areas to Stay in Da Nang 2026 — Peaceful Hotels Guide',u:'da-nang-quiet-areas-hotels.html',c:'Area Guide',e:'Where to stay in Da Nang if you want peace and quiet. Non Nuoc, Son Tra, northern My Khe, and which hotels are genuinely away from noise. Honest guide.',p:30,k:'quietest areas to stay in da nang 2026 — peaceful hotels guide where to stay in da nang if you want peace and quiet. non nuoc, son tra, northern my khe, and which hotels are genuinely away from noise. honest guide. da nang quiet areas hotels'},
  {t:'Da Nang SIM Card Guide 2026 — Best Options and Where to Buy',u:'da-nang-sim-card-guide.html',c:'Travel Guide',e:'Best SIM cards for tourists in Da Nang 2026. Viettel, Vietnamobile, eSIM options. Where to buy, prices, and which plan works best.',p:30,k:'da nang sim card guide 2026 — best options and where to buy best sim cards for tourists in da nang 2026. viettel, vietnamobile, esim options. where to buy, prices, and which plan works best. da nang sim card guide'},
  {t:'Best Da Nang Videos 2026, Travel, Food & Beaches',u:'da-nang-videos.html',c:'Content',e:'The best YouTube videos about Da Nang in 2026, travel guides, street food tours, beach walks, and drone footage. Curated for visitors planning their trip.',p:30,k:'best da nang videos 2026, travel, food & beaches the best youtube videos about da nang in 2026, travel guides, street food tours, beach walks, and drone footage. curated for visitors planning their trip. da nang videos'},
  {t:'Vietnam Visa & Visa Runs from Da Nang (2026 Guide)',u:'da-nang-visa-run-guide.html',c:'Travel Guide',e:'Vietnam e-visa and visa run guide from Da Nang for 2026. E-visa costs $25, Lao Bao border details, flight runs, and what expats actually do. Updated rules.',p:30,k:'vietnam visa & visa runs from da nang (2026 guide) vietnam e-visa and visa run guide from da nang for 2026. e-visa costs $25, lao bao border details, flight runs, and what expats actually do. updated rules. da nang visa run guide'},
  {t:'Da Nang vs Bali: Which is Better? (2026 Honest Guide)',u:'da-nang-vs-bali.html',c:'Comparison Guide',e:'Da Nang vs Bali 2026 — beaches, culture, hotels, costs, and which destination suits your trip. An honest comparison from a Da Nang local.',p:30,k:'da nang vs bali: which is better? (2026 honest guide) da nang vs bali 2026 — beaches, culture, hotels, costs, and which destination suits your trip. an honest comparison from a da nang local. da nang vs bali'},
  {t:'Da Nang vs Nha Trang 2026 — Which Beach City Wins?',u:'da-nang-vs-nha-trang.html',c:'Comparison Guide',e:'Da Nang vs Nha Trang: which Vietnamese beach city is better for your trip? Honest comparison of hotels, beaches, costs, and what each destination does well.',p:30,k:'da nang vs nha trang 2026 — which beach city wins? da nang vs nha trang: which vietnamese beach city is better for your trip? honest comparison of hotels, beaches, costs, and what each destination does well. da nang vs nha trang'},
  {t:'Da Nang vs Phu Quoc 2026 — Beach Holiday Comparison',u:'da-nang-vs-phu-quoc.html',c:'Comparison Guide',e:'Da Nang vs Phu Quoc island: beaches, resorts, costs, crowds, and practicality. Honest comparison from a local to help you choose the right destination.',p:30,k:'da nang vs phu quoc 2026 — beach holiday comparison da nang vs phu quoc island: beaches, resorts, costs, crowds, and practicality. honest comparison from a local to help you choose the right destination. da nang vs phu quoc'},
  {t:'Furama vs Pullman Da Nang 2026 — Which Family Resort Wins?',u:'furama-vs-pullman-da-nang.html',c:'Comparison Guide',e:'Furama Resort vs Pullman Da Nang Beach: comparing two of the best value beach resorts for families in 2026. Local honest comparison with clear verdict.',p:30,k:'furama vs pullman da nang 2026 — which family resort wins? furama resort vs pullman da nang beach: comparing two of the best value beach resorts for families in 2026. local honest comparison with clear verdict. furama vs pullman da nang'},
  {t:'Hoi An Old Town Hotels 2026, Best Places to Stay Near Ancient Town',u:'hoi-an-old-town-hotels.html',c:'Hoi An Guide',e:'The best hotels near Hoi An',p:30,k:'hoi an old town hotels 2026, best places to stay near ancient town the best hotels near hoi an hoi an old town hotels'},
  {t:'Hyatt Regency vs Furama Da Nang 2026 — Worth the Price Gap?',u:'hyatt-regency-vs-furama-da-nang.html',c:'Comparison Guide',e:'Hyatt Regency vs Furama Resort Da Nang: is the Hyatt worth the extra spend? Honest comparison of facilities, beach, value, and who each suits best.',p:30,k:'hyatt regency vs furama da nang 2026 — worth the price gap? hyatt regency vs furama resort da nang: is the hyatt worth the extra spend? honest comparison of facilities, beach, value, and who each suits best. hyatt regency vs furama da nang'},
  {t:'Hyatt Regency vs Marriott Da Nang 2026, Which Wins?',u:'hyatt-vs-marriott-da-nang.html',c:'Comparison Guide',e:'Hyatt Regency Danang vs Da Nang Marriott Resort compared side-by-side for 2026. Pools, rooms, beach access, value, and a clear verdict on which resort to book.',p:30,k:'hyatt regency vs marriott da nang 2026, which wins? hyatt regency danang vs da nang marriott resort compared side-by-side for 2026. pools, rooms, beach access, value, and a clear verdict on which resort to book. hyatt vs marriott da nang'},
  {t:'Is Da Nang Walkable? (Honest 2026 Guide)',u:'is-da-nang-walkable.html',c:'Area Guide',e:'Is Da Nang walkable? Honest answer: it depends heavily on where you stay. Han River area is walkable. Non Nuoc resort zone is not. Full breakdown.',p:30,k:'is da nang walkable? (honest 2026 guide) is da nang walkable? honest answer: it depends heavily on where you stay. han river area is walkable. non nuoc resort zone is not. full breakdown. is da nang walkable'},
  {t:'Mandila Beach vs Stella Maris Da Nang 2026, My Khe Hotels',u:'mandila-beach-vs-stella-maris-da-nang.html',c:'Comparison Guide',e:'Mandila Beach Hotel Da Nang vs Stella Maris Da Nang compared for 2026. Two beachfront My Khe hotels at the upper-mid price tier, amenities, rooms, and which to book.',p:30,k:'mandila beach vs stella maris da nang 2026, my khe hotels mandila beach hotel da nang vs stella maris da nang compared for 2026. two beachfront my khe hotels at the upper-mid price tier, amenities, rooms, and which to book. mandila beach vs stella maris da nang'},
  {t:'Da Nang Marriott Resort & Spa Review (2026)',u:'marriott-resort-da-nang.html',c:'Guide',e:'Da Nang Marriott Resort & Spa review 2026: luxury villas and Quan Spa on Non Nuoc Beach. Bonvoy earning from $175/night. Worth it vs. the Sheraton?',p:30,k:'da nang marriott resort & spa review (2026) da nang marriott resort & spa review 2026: luxury villas and quan spa on non nuoc beach. bonvoy earning from $175/night. worth it vs. the sheraton? marriott resort da nang'},
  {t:'Marriott vs Sheraton Grand Da Nang 2026 — Side-by-Side',u:'marriott-vs-sheraton-da-nang.html',c:'Comparison Guide',e:'Marriott Resort vs Sheraton Grand Da Nang: both on Non Nuoc Beach, both Bonvoy properties. Which is right for your family or couple',p:30,k:'marriott vs sheraton grand da nang 2026 — side-by-side marriott resort vs sheraton grand da nang: both on non nuoc beach, both bonvoy properties. which is right for your family or couple marriott vs sheraton da nang'},
  {t:'Melia Da Nang Beach Review 2026 — My Khe Beachfront',u:'melia-da-nang.html',c:'Guide',e:'Melia Da Nang review 2026: directly on My Khe Beach, Spanish brand reliability, strong pool. Honest assessment of value vs competing hotels at this price.',p:30,k:'melia da nang beach review 2026 — my khe beachfront melia da nang review 2026: directly on my khe beach, spanish brand reliability, strong pool. honest assessment of value vs competing hotels at this price. melia da nang'},
  {t:'Melia Vinpearl Da Nang Review, City Hotel (2026)',u:'melia-vinpearl-da-nang.html',c:'Guide',e:'Melia Vinpearl Da Nang review 2026: Han River city-center hotel next to Vincom Mall. Large rooms, rooftop pool, from $80/night. Best city hotel in Da Nang?',p:30,k:'melia vinpearl da nang review, city hotel (2026) melia vinpearl da nang review 2026: han river city-center hotel next to vincom mall. large rooms, rooftop pool, from $80/night. best city hotel in da nang? melia vinpearl da nang'},
  {t:'Melia vs Hyatt Regency Da Nang 2026 — Beach Resort Compared',u:'melia-vs-hyatt-regency-da-nang.html',c:'Comparison Guide',e:'Melia Da Nang Beach vs Hyatt Regency: honest comparison of two of Da Nang',p:30,k:'melia vs hyatt regency da nang 2026 — beach resort compared melia da nang beach vs hyatt regency: honest comparison of two of da nang melia vs hyatt regency da nang'},
  {t:'Melia vs Radisson Blu Danang 2026, Which Is Better?',u:'melia-vs-radisson-blu-da-nang.html',c:'Comparison Guide',e:'Melia Danang vs Radisson Blu Danang compared for 2026, two underrated 5-stars on Non Nuoc Beach. Honest verdict on which is better value before you book.',p:30,k:'melia vs radisson blu danang 2026, which is better? melia danang vs radisson blu danang compared for 2026, two underrated 5-stars on non nuoc beach. honest verdict on which is better value before you book. melia vs radisson blu da nang'},
  {t:'Mikazuki Japanese Resort Da Nang Review (2026)',u:'mikazuki-da-nang.html',c:'Guide',e:'Mikazuki Japanese Resorts & Spa Da Nang review 2026: Japanese onsen, waterpark, infinity pool. From $130/night, the most resort-complete property in Da Nang.',p:30,k:'mikazuki japanese resort da nang review (2026) mikazuki japanese resorts & spa da nang review 2026: japanese onsen, waterpark, infinity pool. from $130/night, the most resort-complete property in da nang. mikazuki da nang'},
  {t:'Muong Thanh Luxury Da Nang Review (2026)',u:'muong-thanh-luxury-da-nang.html',c:'Luxury Hotels',e:'Muong Thanh Luxury Da Nang review 2026: Vietnamese-owned 5-star on My Khe Beach, large rooms from $55/night. Is it Da Nang',p:30,k:'muong thanh luxury da nang review (2026) muong thanh luxury da nang review 2026: vietnamese-owned 5-star on my khe beach, large rooms from $55/night. is it da nang muong thanh luxury da nang'},
  {t:'Da Nang Travel News 2026, Latest Flights & Updates',u:'news.html',c:'Content',e:'Latest Da Nang travel news for 2026, new flight routes, tourism developments, fireworks festival dates, and hotel openings. Updated by a local expat.',p:30,k:'da nang travel news 2026, latest flights & updates latest da nang travel news for 2026, new flight routes, tourism developments, fireworks festival dates, and hotel openings. updated by a local expat. news'},
  {t:'Non Nuoc Beach Da Nang, Complete Guide 2026',u:'non-nuoc-beach-da-nang.html',c:'Beach & Coastal',e:'Non Nuoc Beach Da Nang guide 2026: calmer waves, wider sand, fewer crowds, and Da Nang',p:30,k:'non nuoc beach da nang, complete guide 2026 non nuoc beach da nang guide 2026: calmer waves, wider sand, fewer crowds, and da nang non nuoc beach da nang'},
  {t:'Premier Village Danang Resort Review (2026)',u:'premier-village-da-nang.html',c:'Guide',e:'Premier Village Danang review 2026: all-villa resort on Son Tra Peninsula, private pools, family villas from $200/night. Is the premium worth it?',p:30,k:'premier village danang resort review (2026) premier village danang review 2026: all-villa resort on son tra peninsula, private pools, family villas from $200/night. is the premium worth it? premier village da nang'},
  {t:'Pullman vs Hyatt Regency Da Nang 2026 — My Khe vs Non Nuoc',u:'pullman-vs-hyatt-regency-da-nang.html',c:'Comparison Guide',e:'Pullman Da Nang Beach Resort vs Hyatt Regency Da Nang: My Khe proximity vs Non Nuoc resort scale. Which fits your trip better? Local comparison.',p:30,k:'pullman vs hyatt regency da nang 2026 — my khe vs non nuoc pullman da nang beach resort vs hyatt regency da nang: my khe proximity vs non nuoc resort scale. which fits your trip better? local comparison. pullman vs hyatt regency da nang'},
  {t:'Pullman vs Sheraton Grand Da Nang 2026 — Compared Honestly',u:'pullman-vs-sheraton-da-nang.html',c:'Comparison Guide',e:'Pullman Da Nang Beach vs Sheraton Grand: price, pool, beach quality and who each hotel suits. Honest local comparison for 2026.',p:30,k:'pullman vs sheraton grand da nang 2026 — compared honestly pullman da nang beach vs sheraton grand: price, pool, beach quality and who each hotel suits. honest local comparison for 2026. pullman vs sheraton da nang'},
  {t:'Radisson Blu Resort Danang Review, Worth It? (2026)',u:'radisson-blu-da-nang.html',c:'Guide',e:'Radisson Blu Resort Danang review 2026: stylish Non Nuoc beachfront resort from $100/night. Consistently underrated, one of Da Nang',p:30,k:'radisson blu resort danang review, worth it? (2026) radisson blu resort danang review 2026: stylish non nuoc beachfront resort from $100/night. consistently underrated, one of da nang radisson blu da nang'},
  {t:'Azura Da Nang Hotel, Full Review 2026',u:'review-azura-da-nang.html',c:'Hotel Review',e:'Azura Da Nang Hotel full review 2026: Han River boutique with more character than the big brands for less money. From $65/night, complete honest rating.',p:30,k:'azura da nang hotel, full review 2026 azura da nang hotel full review 2026: han river boutique with more character than the big brands for less money. from $65/night, complete honest rating. review azura da nang'},
  {t:'Brilliant Hotel Da Nang — Full Review 2026',u:'review-brilliant-hotel-da-nang.html',c:'Hotel Review',e:'Full Brilliant Hotel Da Nang review 2026. Budget-friendly riverfront with rooftop pool, walking distance to Han Market. Best affordable city hotel?',p:30,k:'brilliant hotel da nang — full review 2026 full brilliant hotel da nang review 2026. budget-friendly riverfront with rooftop pool, walking distance to han market. best affordable city hotel? review brilliant hotel da nang'},
  {t:'Four Points by Sheraton Danang, Full Review 2026',u:'review-four-points-sheraton-da-nang.html',c:'Hotel Review',e:'Four Points by Sheraton Danang full review 2026: reliable 4-star on My Khe Beach, strong breakfast, from $80/night. Worth it vs better-value alternatives?',p:30,k:'four points by sheraton danang, full review 2026 four points by sheraton danang full review 2026: reliable 4-star on my khe beach, strong breakfast, from $80/night. worth it vs better-value alternatives? review four points sheraton da nang'},
  {t:'Furama Resort Da Nang — Full Review 2026',u:'review-furama-resort-da-nang.html',c:'Hotel Review',e:'Full Furama Resort Da Nang review 2026. Da Nang',p:30,k:'furama resort da nang — full review 2026 full furama resort da nang review 2026. da nang review furama resort da nang'},
  {t:'Fusion Suites Da Nang Beach, Full Review 2026',u:'review-fusion-suites-da-nang.html',c:'Hotel Review',e:'Fusion Suites Da Nang full review 2026: all-suite beachfront with spa-inclusive twice-daily breakfast. From $95/night, the most unusual value in Da Nang.',p:30,k:'fusion suites da nang beach, full review 2026 fusion suites da nang full review 2026: all-suite beachfront with spa-inclusive twice-daily breakfast. from $95/night, the most unusual value in da nang. review fusion suites da nang'},
  {t:'Grand Mercure Da Nang — Full Hotel Review 2026',u:'review-grand-mercure-da-nang.html',c:'Hotel Review',e:'Full Grand Mercure Da Nang review 2026. Riverfront serviced apartments, strong value for longer stays. Best for families or digital nomads staying a week+.',p:30,k:'grand mercure da nang — full hotel review 2026 full grand mercure da nang review 2026. riverfront serviced apartments, strong value for longer stays. best for families or digital nomads staying a week+. review grand mercure da nang'},
  {t:'Hilton Da Nang — Full Hotel Review 2026',u:'review-hilton-da-nang.html',c:'Hotel Review',e:'Full Hilton Da Nang review 2026. Riverfront, rooftop pool, business-class reliability. The best 5-star city hotel on the Han River? Honest assessment.',p:30,k:'hilton da nang — full hotel review 2026 full hilton da nang review 2026. riverfront, rooftop pool, business-class reliability. the best 5-star city hotel on the han river? honest assessment. review hilton da nang'},
  {t:'Marriott Resort Da Nang — Full Review 2026',u:'review-marriott-resort-da-nang.html',c:'Hotel Review',e:'Full Marriott Resort & Spa Da Nang review. My Khe beachfront, massive pool, Bonvoy points. Who it suits best and what the honest trade-offs are in 2026.',p:30,k:'marriott resort da nang — full review 2026 full marriott resort & spa da nang review. my khe beachfront, massive pool, bonvoy points. who it suits best and what the honest trade-offs are in 2026. review marriott resort da nang'},
  {t:'Melia Da Nang Beach — Full Hotel Review 2026',u:'review-melia-da-nang.html',c:'Hotel Review',e:'Full Melia Da Nang Beach review 2026. Directly on My Khe, Spanish brand reliability, strong pool. Worth the rates vs cheaper My Khe alternatives?',p:30,k:'melia da nang beach — full hotel review 2026 full melia da nang beach review 2026. directly on my khe, spanish brand reliability, strong pool. worth the rates vs cheaper my khe alternatives? review melia da nang'},
  {t:'Melia Vinpearl Da Nang, Full Review 2026',u:'review-melia-vinpearl-da-nang.html',c:'Hotel Review',e:'Melia Vinpearl Da Nang full review 2026: Han River city-center hotel next to Vincom Mall. Large rooms, rooftop pool, from $80/night. Best city hotel here?',p:30,k:'melia vinpearl da nang, full review 2026 melia vinpearl da nang full review 2026: han river city-center hotel next to vincom mall. large rooms, rooftop pool, from $80/night. best city hotel here? review melia vinpearl da nang'},
  {t:'Mikazuki Japanese Resort Da Nang — Full Review 2026',u:'review-mikazuki-da-nang.html',c:'Hotel Review',e:'Full Mikazuki Da Nang review 2026. Japanese-themed resort with water park, private beach, and onsen. Best budget family resort in Da Nang? Honest verdict.',p:30,k:'mikazuki japanese resort da nang — full review 2026 full mikazuki da nang review 2026. japanese-themed resort with water park, private beach, and onsen. best budget family resort in da nang? honest verdict. review mikazuki da nang'},
  {t:'Muong Thanh Luxury Da Nang — Full Review 2026',u:'review-muong-thanh-luxury-da-nang.html',c:'Hotel Review',e:'Full Muong Thanh Luxury Da Nang review 2026. Vietnam',p:30,k:'muong thanh luxury da nang — full review 2026 full muong thanh luxury da nang review 2026. vietnam review muong thanh luxury da nang'},
  {t:'Premier Village Da Nang Resort — Full Review 2026',u:'review-premier-village-da-nang.html',c:'Hotel Review',e:'Full Premier Village Da Nang review 2026. Private-pool villas on a headland, dramatic setting. The best villa resort in Da Nang? Honest local review.',p:30,k:'premier village da nang resort — full review 2026 full premier village da nang review 2026. private-pool villas on a headland, dramatic setting. the best villa resort in da nang? honest local review. review premier village da nang'},
  {t:'Radisson Blu Resort Da Nang — Full Review 2026',u:'review-radisson-blu-da-nang.html',c:'Hotel Review',e:'Full Radisson Blu Resort Da Nang review. Son Tra Peninsula private beach, sea-view rooms, quieter than My Khe. Good alternative to the InterContinental?',p:30,k:'radisson blu resort da nang — full review 2026 full radisson blu resort da nang review. son tra peninsula private beach, sea-view rooms, quieter than my khe. good alternative to the intercontinental? review radisson blu da nang'},
  {t:'TMS Hotel Da Nang Beach — Full Review 2026',u:'review-tms-hotel-da-nang.html',c:'Hotel Review',e:'Full TMS Hotel Da Nang Beach review 2026. 40th-floor rooftop infinity pool, My Khe beachfront. Best mid-luxury option on the main strip?',p:30,k:'tms hotel da nang beach — full review 2026 full tms hotel da nang beach review 2026. 40th-floor rooftop infinity pool, my khe beachfront. best mid-luxury option on the main strip? review tms hotel da nang'},
  {t:'Wyndham Soleil Danang, Full Review 2026',u:'review-wyndham-soleil-da-nang.html',c:'Hotel Review',e:'Wyndham Soleil Danang full review 2026: My Khe Beach high-rise, apartment-style rooms with sea views. From $75/night, good for longer stays. Full review.',p:30,k:'wyndham soleil danang, full review 2026 wyndham soleil danang full review 2026: my khe beach high-rise, apartment-style rooms with sea views. from $75/night, good for longer stays. full review. review wyndham soleil da nang'},
  {t:'Sheraton vs Hyatt Regency Da Nang 2026 — Family Resort Showdown',u:'sheraton-vs-hyatt-regency-da-nang.html',c:'Comparison Guide',e:'Sheraton Grand vs Hyatt Regency Da Nang: pool complexes, beach quality, kids clubs. Which family resort wins in 2026? Honest local comparison.',p:30,k:'sheraton vs hyatt regency da nang 2026 — family resort showdown sheraton grand vs hyatt regency da nang: pool complexes, beach quality, kids clubs. which family resort wins in 2026? honest local comparison. sheraton vs hyatt regency da nang'},
  {t:'Silk Path Grand Resort Danang Review (2026)',u:'silk-path-grand-da-nang.html',c:'Guide',e:'Silk Path Grand Resort & Spa Danang review 2026: My Khe Beach spa resort from a Vietnamese brand. From $90/night, honest assessment of what you actually get.',p:30,k:'silk path grand resort danang review (2026) silk path grand resort & spa danang review 2026: my khe beach spa resort from a vietnamese brand. from $90/night, honest assessment of what you actually get. silk path grand da nang'},
  {t:'TIA Wellness Resort Da Nang Review, Worth It? (2026)',u:'tia-wellness-resort-da-nang.html',c:'Guide',e:'TIA Wellness Resort Da Nang review 2026: all-inclusive wellness on Non Nuoc Beach, spa and yoga focus. From $160/night, is the concept worth the premium?',p:30,k:'tia wellness resort da nang review, worth it? (2026) tia wellness resort da nang review 2026: all-inclusive wellness on non nuoc beach, spa and yoga focus. from $160/night, is the concept worth the premium? tia wellness resort da nang'},
  {t:'TMS Hotel Da Nang Beach Review, Worth It? (2026)',u:'tms-hotel-da-nang.html',c:'Guide',e:'TMS Hotel Da Nang Beach review 2026: direct My Khe beachfront, rooftop pool, from $50/night. Is it Da Nang',p:30,k:'tms hotel da nang beach review, worth it? (2026) tms hotel da nang beach review 2026: direct my khe beachfront, rooftop pool, from $50/night. is it da nang tms hotel da nang'},
  {t:'TMS Hotel vs Sala Danang Beach 2026, My Khe Hotel Compared',u:'tms-hotel-vs-sala-danang-beach.html',c:'Comparison Guide',e:'TMS Hotel Da Nang Beach vs Sala Danang Beach Hotel compared for 2026. Two mid-upper My Khe Beach hotels side-by-side, amenities, location, value, and which to book.',p:30,k:'tms hotel vs sala danang beach 2026, my khe hotel compared tms hotel da nang beach vs sala danang beach hotel compared for 2026. two mid-upper my khe beach hotels side-by-side, amenities, location, value, and which to book. tms hotel vs sala danang beach'},
  {t:'Vinpearl Luxury Da Nang Review, Worth It? (2026)',u:'vinpearl-luxury-da-nang.html',c:'Luxury Hotels',e:'Vinpearl Luxury Da Nang review 2026: premium Vietnamese-brand resort on Non Nuoc Beach from $130/night. Worth it vs. international brands? Full verdict.',p:30,k:'vinpearl luxury da nang review, worth it? (2026) vinpearl luxury da nang review 2026: premium vietnamese-brand resort on non nuoc beach from $130/night. worth it vs. international brands? full verdict. vinpearl luxury da nang'},
  {t:'What to Pack for Da Nang 2026 — The Practical Packing List',u:'what-to-pack-for-da-nang.html',c:'Practical Guide',e:'Practical packing list for Da Nang 2026. Seasonal packing for dry vs wet season, beach essentials, motorbike gear, power adapters, healthcare items, and what NOT to bring.',p:30,k:'what to pack for da nang 2026 — the practical packing list practical packing list for da nang 2026. seasonal packing for dry vs wet season, beach essentials, motorbike gear, power adapters, healthcare items, and what not to bring. what to pack for da nang'},
  {t:'Wyndham Soleil Danang Review, My Khe Beach (2026)',u:'wyndham-soleil-da-nang.html',c:'Guide',e:'Wyndham Soleil Danang review 2026: My Khe Beach high-rise with apartment-style rooms and sea views. From $75/night, good for longer stays. Full review.',p:30,k:'wyndham soleil danang review, my khe beach (2026) wyndham soleil danang review 2026: my khe beach high-rise with apartment-style rooms and sea views. from $75/night, good for longer stays. full review. wyndham soleil da nang'},
  {t:'About Da Nang Hotel Guide — Local Expat Reviews Since 2022',u:'about.html',c:'Site',e:'Da Nang Hotel Guide is written by Ryan Yousefi, an American living in Da Nang since 2022. How we review hotels, our editorial standards, and why we built this.',p:25,k:'about da nang hotel guide — local expat reviews since 2022 da nang hotel guide is written by ryan yousefi, an american living in da nang since 2022. how we review hotels, our editorial standards, and why we built this. about'}
];

var SYN = {
  'dining':['dining','food','restaurant','restaurants','eat','eating','cafe','cafes','michelin','bars','nightlife','cuisine','pho','banh mi','brunch','breakfast','dinner','drinks','street food'],
  'food':['food','dining','restaurant','eat','eating','cuisine','pho','banh mi','street food','michelin','where to eat'],
  'restaurant':['restaurant','restaurants','dining','food','eat','michelin','cuisine'],
  'bar':['bar','bars','nightlife','cocktails','drinks','craft beer','rooftop bar'],
  'bars':['bars','bar','nightlife','cocktails','drinks','craft beer','rooftop bar','happy hour'],
  'nightlife':['nightlife','bars','bar','clubs','evening','night out','dragon bridge fire'],
  'cafe':['cafe','cafes','coffee','brunch','an thuong'],
  'cafes':['cafes','cafe','coffee','brunch','specialty coffee'],
  'michelin':['michelin','dining','restaurant','food'],
  'marble':['marble','marble mountains','non nuoc','caves','pagoda'],
  'marble mountains':['marble mountains','marble','non nuoc','caves','pagoda','chua tam thai'],
  'dragon bridge':['dragon bridge','han river','fire show','bridge','night show'],
  'ba na hills':['ba na hills','golden bridge','cable car','french village','sun world'],
  'son tra':['son tra','monkey mountain','peninsula','nature','viewpoint'],
  'han river':['han river','riverside','dragon bridge','waterfront'],
  'beach':['beach','my khe','non nuoc','beachfront','coastal','swimming','surf'],
  'my khe':['my khe','my khe beach','beach','beachfront'],
  'non nuoc':['non nuoc','beach','marble mountains'],
  'family':['family','kids','children','kid','waterpark','kids club','lazy river','connecting rooms'],
  'kids':['kids','family','children','kid','waterpark','kids club'],
  'luxury':['luxury','5-star','five star','premium','resort','villas','villa'],
  'resort':['resort','luxury','5-star','hotel','beach resort','spa resort'],
  'budget':['budget','cheap','affordable','value','low cost','cost','how much'],
  'cheap':['cheap','budget','affordable','value'],
  'airport':['airport','dad','da nang airport','arrivals','departure','transfer','grab from airport'],
  'transfer':['transfer','airport','transport','taxi','grab'],
  'transport':['transport','getting around','grab','taxi','motorbike','scooter','bus'],
  'spa':['spa','wellness','massage','treatment','relaxation','tia wellness','naman','fusion'],
  'rooftop':['rooftop','rooftop pool','sky pool','infinity pool','views'],
  'pool':['pool','swimming pool','infinity pool','rooftop pool','lazy river'],
  'couples':['couples','couple','honeymoon','romantic','romance','adults only'],
  'honeymoon':['honeymoon','romantic','couples','villas','private pool'],
  'shopping':['shopping','mall','market','markets','vincom','souvenirs'],
  'hoi an':['hoi an','hoi an ancient town','old town','lanterns','day trip hoi an'],
  'first time':['first time','first trip','beginner','start here','first-time visitor'],
  'itinerary':['itinerary','3 day','3-day','5 day','7 day','day by day','schedule','plan'],
  'weather':['weather','climate','rain','dry season','rainy season','monsoon','best time','when to go'],
  'best time':['best time','when to go','weather','dry season'],
  'rainy':['rainy','rain','monsoon','wet season','typhoon'],
  'villas':['villas','villa','private pool','luxury','couples'],
  'rooftop pool':['rooftop pool','infinity pool','pool','views'],
};

function expandQuery(q) {
  var ql = q.toLowerCase().trim();
  var terms = {}; terms[ql] = 3;
  for (var key in SYN) {
    var kl = key.toLowerCase();
    var syns = SYN[key];
    var hit = (ql===kl || ql.indexOf(kl)!==-1 || kl.indexOf(ql)!==-1);
    if (!hit) { for (var i=0;i<syns.length;i++){ if(ql===syns[i]||ql.indexOf(syns[i])!==-1){hit=true;break;} } }
    if (hit) {
      terms[kl]=(terms[kl]||0)+1;
      for (var i=0;i<syns.length;i++){ terms[syns[i]]=(terms[syns[i]]||0)+0.5; }
    }
  }
  return terms;
}

function scoreItem(item, tw, origQ) {
  var ql=origQ.toLowerCase().trim();
  var tl=item.t.toLowerCase();
  var kl=(item.k||'').toLowerCase();
  var cl=item.c.toLowerCase();
  var el=item.e.toLowerCase();
  var slug=item.u.replace('.html','').replace(/-/g,' ');
  var s=0;
  if(slug===ql||item.u===ql+'.html') s+=200;
  else if(slug.indexOf(ql)!==-1) s+=80;
  if(tl===ql) s+=160;
  else if(tl.indexOf(ql)!==-1){
    if(tl.indexOf('best '+ql)!==-1||tl.indexOf(ql+' guide')!==-1||tl.indexOf(ql+' hotel')!==-1) s+=100;
    else s+=60;
  }
  for(var term in tw){
    var w=tw[term];
    if(term.length<3) continue;
    if(kl.indexOf(term)!==-1) s+=30*w;
    if(tl.indexOf(term)!==-1) s+=22*w;
    if(cl.indexOf(term)!==-1) s+=12*w;
    if(el.indexOf(term)!==-1) s+=8*w;
    if(slug.indexOf(term)!==-1) s+=18*w;
  }
  if(s>0) s+=item.p*0.8;
  return s;
}

window.runSearch = function(query) {
  if (!query||query.length<2) return [];
  var tw = expandQuery(query);
  var scored=[];
  for(var i=0;i<window.SI.length;i++){
    var s=scoreItem(window.SI[i],tw,query);
    if(s>0) scored.push({item:window.SI[i],score:s});
  }
  scored.sort(function(a,b){return b.score-a.score;});
  return scored.map(function(r){return r.item;});
};

// Also expose as SEARCH_INDEX for backward compat
window.SEARCH_INDEX = window.SI.map(function(e){
  return {title:e.t,url:e.u,cat:e.c,excerpt:e.e};
});

})();
